// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IconEpBellFilled: typeof import('~icons/ep/bell-filled')['default']
    IconsIconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./../src/components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./../src/components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./../src/components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./../src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../src/components/WelcomeItem.vue')['default']
  }
}
